"""Triton kernel code generator for cuda-sage.

Generates production-quality Triton kernels with autotuning configs
for common GPU operations. Output is self-contained Python files ready
to import and run (requires triton + torch).
"""
from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum


class TritonOp(str, Enum):
    ELEMENTWISE = "elementwise"
    REDUCTION   = "reduction"
    MATMUL      = "matmul"
    SOFTMAX     = "softmax"
    LAYERNORM   = "layernorm"
    ATTENTION   = "attention"


class DType(str, Enum):
    FLOAT16  = "float16"
    FLOAT32  = "float32"
    BFLOAT16 = "bfloat16"


@dataclass
class TritonGenResult:
    op: TritonOp
    dtype: DType
    source: str                     # complete Python source, ready to run
    kernel_names: list[str]         # @triton.jit function names in source
    wrapper_names: list[str]        # Python wrapper function names
    autotune_configs: int           # number of autotune configs included
    notes: list[str] = field(default_factory=list)

    def __str__(self) -> str:
        return self.source


class TritonKernelGenerator:
    """Generate optimised Triton kernel source for common GPU operations.

    Parameters
    ----------
    activation:
        Fused activation for elementwise/matmul kernels.
        One of "none", "relu", "gelu", "sigmoid", "silu".
    block_size:
        Default block / tile size hint (power-of-two, 16-512).
    """

    _VALID_ACTIVATIONS = {"none", "relu", "gelu", "sigmoid", "silu"}

    def __init__(self, activation: str = "none", block_size: int = 128) -> None:
        if activation not in self._VALID_ACTIVATIONS:
            raise ValueError(f"activation must be one of {self._VALID_ACTIVATIONS}")
        if block_size < 16 or (block_size & (block_size - 1)) != 0:
            raise ValueError("block_size must be a power-of-two >= 16")
        self.activation = activation
        self.block_size = block_size

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(self, op: TritonOp | str, dtype: DType | str = DType.FLOAT16) -> TritonGenResult:
        op = TritonOp(op)
        dtype = DType(dtype)
        dispatch = {
            TritonOp.ELEMENTWISE: self._gen_elementwise,
            TritonOp.REDUCTION:   self._gen_reduction,
            TritonOp.MATMUL:      self._gen_matmul,
            TritonOp.SOFTMAX:     self._gen_softmax,
            TritonOp.LAYERNORM:   self._gen_layernorm,
            TritonOp.ATTENTION:   self._gen_attention,
        }
        return dispatch[op](dtype)

    # ------------------------------------------------------------------
    # Elementwise
    # ------------------------------------------------------------------

    def _gen_elementwise(self, dtype: DType) -> TritonGenResult:
        tl_dtype = _tl_dtype(dtype)
        act_code, act_note = _activation_snippet(self.activation)
        bs = self.block_size
        act_label = f" + {self.activation}" if self.activation != "none" else ""
        act_comment = f" with {self.activation} activation" if self.activation != "none" else ""
        source = '''"""Triton fused elementwise kernel (op=add__ACT_LABEL__).

Generated by cuda-sage codegen.
Requires: triton>=2.3, torch>=2.1
"""
import torch
import triton
import triton.language as tl

DEVICE = triton.runtime.driver.active.get_active_torch_device()


@triton.autotune(
    configs=[
        triton.Config({"BLOCK_SIZE": __BS8__}, num_warps=8),
        triton.Config({"BLOCK_SIZE": __BS4__}, num_warps=4),
        triton.Config({"BLOCK_SIZE": __BS2__}, num_warps=4),
        triton.Config({"BLOCK_SIZE": __BS1__}, num_warps=2),
    ],
    key=["n_elements"],
)
@triton.jit
def elementwise_add_kernel(
    x_ptr, y_ptr, out_ptr, n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    x = tl.load(x_ptr + offsets, mask=mask).to(tl.float32)
    y = tl.load(y_ptr + offsets, mask=mask).to(tl.float32)
    out = x + y
__ACT_CODE__
    tl.store(out_ptr + offsets, out.to(__TL_DTYPE__), mask=mask)


def elementwise_add(x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
    """Add two tensors element-wise__ACT_COMMENT__."""
    assert x.shape == y.shape
    assert x.is_cuda and y.is_cuda
    out = torch.empty_like(x, dtype=torch.__DTYPE__)
    n_elements = x.numel()
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    elementwise_add_kernel[grid](x, y, out, n_elements)
    return out


if __name__ == "__main__":
    torch.manual_seed(0)
    N = 1 << 20
    x = torch.randn(N, device=DEVICE, dtype=torch.__DTYPE__)
    y = torch.randn(N, device=DEVICE, dtype=torch.__DTYPE__)
    out_tri = elementwise_add(x, y)
    out_ref = (x.float() + y.float()).to(torch.__DTYPE__)
    err = (out_tri.float() - out_ref.float()).abs().max().item()
    print(f"{'OK' if err < 1e-2 else 'FAIL'}  elementwise_add  max_err={err:.2e}")
'''
        source = (
            source
            .replace("__ACT_LABEL__", act_label)
            .replace("__BS8__", str(bs * 8))
            .replace("__BS4__", str(bs * 4))
            .replace("__BS2__", str(bs * 2))
            .replace("__BS1__", str(bs))
            .replace("__ACT_CODE__", act_code.rstrip("\n"))
            .replace("__TL_DTYPE__", tl_dtype)
            .replace("__DTYPE__", dtype.value)
            .replace("__ACT_COMMENT__", act_comment)
        )
        return TritonGenResult(
            op=TritonOp.ELEMENTWISE,
            dtype=dtype,
            source=source,
            kernel_names=["elementwise_add_kernel"],
            wrapper_names=["elementwise_add"],
            autotune_configs=4,
            notes=[act_note] if act_note else [],
        )

    # ------------------------------------------------------------------
    # Reduction
    # ------------------------------------------------------------------

    def _gen_reduction(self, dtype: DType) -> TritonGenResult:
        tl_dtype = _tl_dtype(dtype)
        source = (
            '''"""Triton parallel row reduction (sum + max).

Generated by cuda-sage codegen.
Requires: triton>=2.3, torch>=2.1
"""
import torch
import triton
import triton.language as tl

DEVICE = triton.runtime.driver.active.get_active_torch_device()


@triton.autotune(
    configs=[
        triton.Config({"BLOCK_SIZE": 2048}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 512},  num_warps=4),
        triton.Config({"BLOCK_SIZE": 256},  num_warps=4),
    ],
    key=["n_cols"],
)
@triton.jit
def row_sum_kernel(x_ptr, out_ptr, n_rows, n_cols, stride_row, BLOCK_SIZE: tl.constexpr):
    row = tl.program_id(0)
    row_ptr = x_ptr + row * stride_row
    cols = tl.arange(0, BLOCK_SIZE)
    acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
    for off in tl.range(0, n_cols, BLOCK_SIZE):
        c = off + cols
        x = tl.load(row_ptr + c, mask=c < n_cols, other=0.0).to(tl.float32)
        acc += x
    tl.store(out_ptr + row, tl.sum(acc, axis=0).to(''' + tl_dtype + '''))


@triton.autotune(
    configs=[
        triton.Config({"BLOCK_SIZE": 2048}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 1024}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 512},  num_warps=4),
        triton.Config({"BLOCK_SIZE": 256},  num_warps=4),
    ],
    key=["n_cols"],
)
@triton.jit
def row_max_kernel(x_ptr, out_ptr, n_rows, n_cols, stride_row, BLOCK_SIZE: tl.constexpr):
    row = tl.program_id(0)
    row_ptr = x_ptr + row * stride_row
    cols = tl.arange(0, BLOCK_SIZE)
    acc = tl.full([BLOCK_SIZE], value=float("-inf"), dtype=tl.float32)
    for off in tl.range(0, n_cols, BLOCK_SIZE):
        c = off + cols
        x = tl.load(row_ptr + c, mask=c < n_cols, other=float("-inf")).to(tl.float32)
        acc = tl.maximum(acc, x)
    tl.store(out_ptr + row, tl.max(acc, axis=0).to(''' + tl_dtype + '''))


def row_sum(x: torch.Tensor) -> torch.Tensor:
    assert x.ndim == 2 and x.is_cuda and x.is_contiguous()
    M, N = x.shape
    out = torch.empty(M, device=x.device, dtype=torch.''' + dtype.value + ''')
    row_sum_kernel[(M,)](x, out, M, N, x.stride(0))
    return out


def row_max(x: torch.Tensor) -> torch.Tensor:
    assert x.ndim == 2 and x.is_cuda and x.is_contiguous()
    M, N = x.shape
    out = torch.empty(M, device=x.device, dtype=torch.''' + dtype.value + ''')
    row_max_kernel[(M,)](x, out, M, N, x.stride(0))
    return out


if __name__ == "__main__":
    torch.manual_seed(0)
    M, N = 512, 4096
    x = torch.randn(M, N, device=DEVICE, dtype=torch.''' + dtype.value + ''')
    tri_sum = row_sum(x)
    ref_sum = x.float().sum(dim=1).to(torch.''' + dtype.value + ''')
    err_sum = (tri_sum.float() - ref_sum.float()).abs().max().item()
    tri_max = row_max(x)
    ref_max = x.float().max(dim=1).values.to(torch.''' + dtype.value + ''')
    err_max = (tri_max.float() - ref_max.float()).abs().max().item()
    for name, err in [("row_sum", err_sum), ("row_max", err_max)]:
        print(f"{'OK' if err < 1e-2 else 'FAIL'}  {name}  max_err={err:.2e}")
'''
        )
        return TritonGenResult(
            op=TritonOp.REDUCTION,
            dtype=dtype,
            source=source,
            kernel_names=["row_sum_kernel", "row_max_kernel"],
            wrapper_names=["row_sum", "row_max"],
            autotune_configs=4,
        )

    # ------------------------------------------------------------------
    # Matmul
    # ------------------------------------------------------------------

    def _gen_matmul(self, dtype: DType) -> TritonGenResult:
        tl_dtype = _tl_dtype(dtype)
        activation = self.activation
        source = (
            '''"""Triton blocked matmul with L2-cache-friendly grouped ordering.

Generated by cuda-sage codegen.
Achieves near-cuBLAS performance on A100/H100.
Requires: triton>=2.3, torch>=2.1
"""
import torch
import triton
import triton.language as tl

DEVICE = triton.runtime.driver.active.get_active_torch_device()


def _autotune_configs():
    return [
        triton.Config({"BLOCK_SIZE_M": 128, "BLOCK_SIZE_N": 256, "BLOCK_SIZE_K": 64, "GROUP_SIZE_M": 8}, num_stages=3, num_warps=8),
        triton.Config({"BLOCK_SIZE_M": 64,  "BLOCK_SIZE_N": 256, "BLOCK_SIZE_K": 32, "GROUP_SIZE_M": 8}, num_stages=4, num_warps=4),
        triton.Config({"BLOCK_SIZE_M": 128, "BLOCK_SIZE_N": 128, "BLOCK_SIZE_K": 32, "GROUP_SIZE_M": 8}, num_stages=4, num_warps=4),
        triton.Config({"BLOCK_SIZE_M": 128, "BLOCK_SIZE_N": 64,  "BLOCK_SIZE_K": 32, "GROUP_SIZE_M": 8}, num_stages=4, num_warps=4),
        triton.Config({"BLOCK_SIZE_M": 64,  "BLOCK_SIZE_N": 128, "BLOCK_SIZE_K": 32, "GROUP_SIZE_M": 8}, num_stages=4, num_warps=4),
        triton.Config({"BLOCK_SIZE_M": 128, "BLOCK_SIZE_N": 32,  "BLOCK_SIZE_K": 32, "GROUP_SIZE_M": 8}, num_stages=4, num_warps=4),
    ]


@triton.autotune(configs=_autotune_configs(), key=["M", "N", "K"])
@triton.jit
def matmul_kernel(
    a_ptr, b_ptr, c_ptr,
    M, N, K,
    stride_am, stride_ak,
    stride_bk, stride_bn,
    stride_cm, stride_cn,
    BLOCK_SIZE_M: tl.constexpr, BLOCK_SIZE_N: tl.constexpr, BLOCK_SIZE_K: tl.constexpr,
    GROUP_SIZE_M: tl.constexpr,
    ACTIVATION: tl.constexpr,
):
    """Blocked matmul C = A @ B with grouped L2 reuse ordering.
    A: (M, K)  B: (K, N)  C: (M, N). Accumulates in fp32.
    """
    pid = tl.program_id(axis=0)
    num_pid_m = tl.cdiv(M, BLOCK_SIZE_M)
    num_pid_n = tl.cdiv(N, BLOCK_SIZE_N)
    num_pid_in_group = GROUP_SIZE_M * num_pid_n
    group_id = pid // num_pid_in_group
    first_pid_m = group_id * GROUP_SIZE_M
    group_size_m = min(num_pid_m - first_pid_m, GROUP_SIZE_M)
    pid_m = first_pid_m + ((pid % num_pid_in_group) % group_size_m)
    pid_n = (pid % num_pid_in_group) // group_size_m

    tl.assume(pid_m >= 0)
    tl.assume(pid_n >= 0)
    tl.assume(stride_am > 0)
    tl.assume(stride_ak > 0)
    tl.assume(stride_bk > 0)
    tl.assume(stride_bn > 0)

    offs_am = (pid_m * BLOCK_SIZE_M + tl.arange(0, BLOCK_SIZE_M)) % M
    offs_bn = (pid_n * BLOCK_SIZE_N + tl.arange(0, BLOCK_SIZE_N)) % N
    offs_k  = tl.arange(0, BLOCK_SIZE_K)
    a_ptrs  = a_ptr + (offs_am[:, None] * stride_am + offs_k[None, :] * stride_ak)
    b_ptrs  = b_ptr + (offs_k[:, None]  * stride_bk + offs_bn[None, :] * stride_bn)

    accumulator = tl.zeros((BLOCK_SIZE_M, BLOCK_SIZE_N), dtype=tl.float32)
    for k in range(0, tl.cdiv(K, BLOCK_SIZE_K)):
        a = tl.load(a_ptrs, mask=offs_k[None, :] < K - k * BLOCK_SIZE_K, other=0.0)
        b = tl.load(b_ptrs, mask=offs_k[:, None] < K - k * BLOCK_SIZE_K, other=0.0)
        accumulator = tl.dot(a, b, accumulator)
        a_ptrs += BLOCK_SIZE_K * stride_ak
        b_ptrs += BLOCK_SIZE_K * stride_bk

    if ACTIVATION == "relu":
        accumulator = tl.maximum(accumulator, 0.0)
    elif ACTIVATION == "gelu":
        x = accumulator
        accumulator = 0.5 * x * (1.0 + tl.math.tanh(0.7978845608 * (x + 0.044715 * x * x * x)))
    elif ACTIVATION == "sigmoid":
        accumulator = 1.0 / (1.0 + tl.math.exp(-accumulator))
    elif ACTIVATION == "silu":
        accumulator = accumulator * (1.0 / (1.0 + tl.math.exp(-accumulator)))

    c = accumulator.to(''' + tl_dtype + ''')
    offs_cm = pid_m * BLOCK_SIZE_M + tl.arange(0, BLOCK_SIZE_M)
    offs_cn = pid_n * BLOCK_SIZE_N + tl.arange(0, BLOCK_SIZE_N)
    c_ptrs  = c_ptr + stride_cm * offs_cm[:, None] + stride_cn * offs_cn[None, :]
    c_mask  = (offs_cm[:, None] < M) & (offs_cn[None, :] < N)
    tl.store(c_ptrs, c, mask=c_mask)


def matmul(a: torch.Tensor, b: torch.Tensor, activation: str = "''' + activation + '''") -> torch.Tensor:
    """Blocked matmul: C = A @ B (optionally fused with activation)."""
    assert a.shape[1] == b.shape[0]
    assert a.is_contiguous() and b.is_contiguous()
    M, K = a.shape
    _, N = b.shape
    c = torch.empty((M, N), device=a.device, dtype=torch.''' + dtype.value + ''')
    grid = lambda meta: (triton.cdiv(M, meta["BLOCK_SIZE_M"]) * triton.cdiv(N, meta["BLOCK_SIZE_N"]),)
    matmul_kernel[grid](
        a, b, c, M, N, K,
        a.stride(0), a.stride(1),
        b.stride(0), b.stride(1),
        c.stride(0), c.stride(1),
        ACTIVATION=activation,
    )
    return c


if __name__ == "__main__":
    torch.manual_seed(0)
    M, N, K = 512, 512, 512
    a = torch.randn((M, K), device=DEVICE, dtype=torch.''' + dtype.value + ''')
    b = torch.randn((K, N), device=DEVICE, dtype=torch.''' + dtype.value + ''')
    tri_out = matmul(a, b)
    ref_out = torch.matmul(a, b)
    err = (tri_out.float() - ref_out.float()).abs().max().item()
    print(f"{'OK' if err < 0.5 else 'FAIL'}  matmul  max_err={err:.3f}")
'''
        )
        return TritonGenResult(
            op=TritonOp.MATMUL,
            dtype=dtype,
            source=source,
            kernel_names=["matmul_kernel"],
            wrapper_names=["matmul"],
            autotune_configs=6,
            notes=[f"Fused {self.activation} activation."] if self.activation != "none" else [],
        )

    # ------------------------------------------------------------------
    # Softmax
    # ------------------------------------------------------------------

    def _gen_softmax(self, dtype: DType) -> TritonGenResult:
        tl_dtype = _tl_dtype(dtype)
        source = (
            '''"""Triton numerically-stable fused row-wise softmax.

Generated by cuda-sage codegen.
Fuses max-subtract -> exp -> sum -> divide in one kernel pass.
Requires: triton>=2.3, torch>=2.1
"""
import torch
import triton
import triton.language as tl

DEVICE = triton.runtime.driver.active.get_active_torch_device()


@triton.jit
def softmax_kernel(
    out_ptr, x_ptr, stride_x_row, stride_out_row,
    n_rows, n_cols,
    BLOCK_SIZE: tl.constexpr,
    num_stages: tl.constexpr,
):
    """Fused row-wise numerically-stable softmax (persistent-program style)."""
    row_start = tl.program_id(0)
    row_step  = tl.num_programs(0)
    for row_idx in tl.range(row_start, n_rows, row_step, num_stages=num_stages):
        row_ptr     = x_ptr   + row_idx * stride_x_row
        out_row_ptr = out_ptr + row_idx * stride_out_row
        col_offsets = tl.arange(0, BLOCK_SIZE)
        mask        = col_offsets < n_cols
        row         = tl.load(row_ptr + col_offsets, mask=mask, other=-float("inf"))
        row_m       = row - tl.max(row, axis=0)
        num         = tl.exp(row_m)
        den         = tl.sum(num, axis=0)
        out         = (num / den).to(''' + tl_dtype + ''')
        tl.store(out_row_ptr + col_offsets, out, mask=mask)


def softmax(x: torch.Tensor) -> torch.Tensor:
    """Row-wise softmax. x: 2-D CUDA tensor. Returns same shape/dtype."""
    assert x.ndim == 2 and x.is_cuda
    n_rows, n_cols = x.shape
    BLOCK_SIZE = triton.next_power_of_2(n_cols)
    num_stages = 4
    num_warps  = 8
    try:
        props = triton.runtime.driver.active.utils.get_device_properties(x.device.index)
        num_sm = props["multiprocessor_count"]
        size_smem = props["max_shared_mem"]
        num_stages = 4 if size_smem > 200_000 else 2
        kernel = softmax_kernel.warmup(
            torch.empty_like(x), x, x.stride(0), x.stride(0),
            n_rows, n_cols, BLOCK_SIZE=BLOCK_SIZE, num_stages=num_stages,
            num_warps=num_warps, grid=(1,),
        )
        kernel._init_handles()
        occ = props["max_num_regs"] // (kernel.n_regs * 32 * num_warps)
        occ = min(occ, size_smem // max(kernel.metadata.shared, 1))
        num_programs = min(num_sm * occ, n_rows)
    except Exception:
        num_programs = n_rows
    y = torch.empty_like(x, dtype=torch.''' + dtype.value + ''')
    softmax_kernel[(num_programs, 1, 1)](
        y, x, x.stride(0), y.stride(0), n_rows, n_cols,
        BLOCK_SIZE=BLOCK_SIZE, num_stages=num_stages,
    )
    return y


if __name__ == "__main__":
    torch.manual_seed(0)
    x = torch.randn(1823, 781, device=DEVICE, dtype=torch.''' + dtype.value + ''')
    tri = softmax(x)
    ref = torch.softmax(x, dim=1).to(torch.''' + dtype.value + ''')
    err = (tri.float() - ref.float()).abs().max().item()
    print(f"{'OK' if err < 1e-2 else 'FAIL'}  softmax  max_err={err:.2e}")
'''
        )
        return TritonGenResult(
            op=TritonOp.SOFTMAX,
            dtype=dtype,
            source=source,
            kernel_names=["softmax_kernel"],
            wrapper_names=["softmax"],
            autotune_configs=0,
            notes=["Persistent-program launch; BLOCK_SIZE = next_power_of_2(N_cols)."],
        )

    # ------------------------------------------------------------------
    # Layer Norm
    # ------------------------------------------------------------------

    def _gen_layernorm(self, dtype: DType) -> TritonGenResult:
        tl_dtype = _tl_dtype(dtype)
        source = (
            '''"""Triton fused forward layer normalization.

Generated by cuda-sage codegen.
Fuses mean, variance, normalize, and affine transform in one pass.
Requires: triton>=2.3, torch>=2.1
"""
import torch
import triton
import triton.language as tl

DEVICE = triton.runtime.driver.active.get_active_torch_device()


@triton.jit
def layer_norm_fwd_kernel(
    X, Y, W, B, Mean, Rstd,
    stride, N, eps,
    BLOCK_SIZE: tl.constexpr,
):
    """Fused LayerNorm forward: Y = (X - mean) / std * W + B. One program per row."""
    row = tl.program_id(0)
    Y += row * stride
    X += row * stride

    _mean = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
    for off in range(0, N, BLOCK_SIZE):
        cols = off + tl.arange(0, BLOCK_SIZE)
        a = tl.load(X + cols, mask=cols < N, other=0.0).to(tl.float32)
        _mean += a
    mean = tl.sum(_mean, axis=0) / N

    _var = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
    for off in range(0, N, BLOCK_SIZE):
        cols = off + tl.arange(0, BLOCK_SIZE)
        x = tl.load(X + cols, mask=cols < N, other=0.0).to(tl.float32)
        x = tl.where(cols < N, x - mean, 0.0)
        _var += x * x
    var  = tl.sum(_var, axis=0) / N
    rstd = 1.0 / tl.sqrt(var + eps)
    tl.store(Mean + row, mean)
    tl.store(Rstd + row, rstd)

    for off in range(0, N, BLOCK_SIZE):
        cols = off + tl.arange(0, BLOCK_SIZE)
        mask = cols < N
        w = tl.load(W + cols, mask=mask).to(tl.float32)
        b = tl.load(B + cols, mask=mask).to(tl.float32)
        x = tl.load(X + cols, mask=mask, other=0.0).to(tl.float32)
        y = (x - mean) * rstd * w + b
        tl.store(Y + cols, y.to(''' + tl_dtype + '''), mask=mask)


def layer_norm(x, weight, bias, eps=1e-5):
    """LayerNorm forward. Returns (y, mean, rstd)."""
    x_2d = x.reshape(-1, x.shape[-1])
    M, N = x_2d.shape
    assert x_2d.is_contiguous()
    MAX_FUSED = 65_536 // x.element_size()
    BLOCK_SIZE = min(MAX_FUSED, triton.next_power_of_2(N))
    if N > BLOCK_SIZE:
        raise RuntimeError(f"layer_norm: feature dim {N} exceeds 64 KB limit")
    num_warps = min(max(BLOCK_SIZE // 256, 1), 8)
    y    = torch.empty_like(x_2d, dtype=torch.''' + dtype.value + ''')
    mean = torch.empty(M, dtype=torch.float32, device=x.device)
    rstd = torch.empty(M, dtype=torch.float32, device=x.device)
    layer_norm_fwd_kernel[(M,)](
        x_2d, y, weight, bias, mean, rstd,
        x_2d.stride(0), N, eps,
        BLOCK_SIZE=BLOCK_SIZE, num_warps=num_warps, num_ctas=1,
    )
    return y.reshape(x.shape), mean, rstd


if __name__ == "__main__":
    torch.manual_seed(0)
    M, N = 512, 1024
    x = torch.randn(M, N, device=DEVICE, dtype=torch.''' + dtype.value + ''')
    w = torch.ones(N, device=DEVICE, dtype=torch.''' + dtype.value + ''')
    b = torch.zeros(N, device=DEVICE, dtype=torch.''' + dtype.value + ''')
    tri_y, _, _ = layer_norm(x, w, b)
    ref_y = torch.nn.functional.layer_norm(x, (N,), w, b).to(torch.''' + dtype.value + ''')
    err = (tri_y.float() - ref_y.float()).abs().max().item()
    print(f"{'OK' if err < 1e-2 else 'FAIL'}  layer_norm  max_err={err:.2e}")
'''
        )
        return TritonGenResult(
            op=TritonOp.LAYERNORM,
            dtype=dtype,
            source=source,
            kernel_names=["layer_norm_fwd_kernel"],
            wrapper_names=["layer_norm"],
            autotune_configs=0,
            notes=["Saves mean/rstd for backward pass compatibility."],
        )

    # ------------------------------------------------------------------
    # Flash Attention
    # ------------------------------------------------------------------

    def _gen_attention(self, dtype: DType) -> TritonGenResult:
        tl_dtype = _tl_dtype(dtype)
        source = (
            '''"""Triton Flash Attention (causal / non-causal) — online-softmax trick.

Generated by cuda-sage codegen.
Avoids materializing the full (Sq x Sk) attention matrix in HBM.
Memory: O(seq_len) vs O(seq_len^2) for naive attention.
Requires: triton>=2.3, torch>=2.1
"""
import math
import torch
import triton
import triton.language as tl

DEVICE = triton.runtime.driver.active.get_active_torch_device()


@triton.autotune(
    configs=[
        triton.Config({"BLOCK_M": 128, "BLOCK_N": 64}, num_stages=4, num_warps=8),
        triton.Config({"BLOCK_M": 64,  "BLOCK_N": 64}, num_stages=4, num_warps=4),
        triton.Config({"BLOCK_M": 128, "BLOCK_N": 32}, num_stages=4, num_warps=4),
        triton.Config({"BLOCK_M": 64,  "BLOCK_N": 32}, num_stages=4, num_warps=2),
    ],
    key=["seq_len_q", "seq_len_k", "head_dim"],
)
@triton.jit
def flash_attn_kernel(
    Q_ptr, K_ptr, V_ptr, Out_ptr, L_ptr,
    stride_qb, stride_qh, stride_qm, stride_qk,
    stride_kb, stride_kh, stride_kn, stride_kk,
    stride_vb, stride_vh, stride_vn, stride_vk,
    stride_ob, stride_oh, stride_om, stride_ok,
    batch_size, num_heads, seq_len_q, seq_len_k, head_dim,
    scale,
    CAUSAL: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_D: tl.constexpr,
):
    """Flash Attention forward (online-softmax).

    Each program handles one (batch, head, BLOCK_M query tile).
    Running max m_i and log-sum-exp l_i track the softmax denominator
    without materializing the full attention matrix.
    CAUSAL=True applies a lower-triangular mask.
    """
    start_m = tl.program_id(0)
    off_bh  = tl.program_id(1)
    off_b   = off_bh // num_heads
    off_h   = off_bh  % num_heads

    Q_ptr   += off_b * stride_qb + off_h * stride_qh
    K_ptr   += off_b * stride_kb + off_h * stride_kh
    V_ptr   += off_b * stride_vb + off_h * stride_vh
    Out_ptr += off_b * stride_ob + off_h * stride_oh

    offs_m = start_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_d = tl.arange(0, BLOCK_D)

    m_i = tl.full([BLOCK_M], value=float("-inf"), dtype=tl.float32)
    l_i = tl.zeros([BLOCK_M], dtype=tl.float32)
    acc = tl.zeros([BLOCK_M, BLOCK_D], dtype=tl.float32)

    q = tl.load(
        Q_ptr + offs_m[:, None] * stride_qm + offs_d[None, :] * stride_qk,
        mask=(offs_m[:, None] < seq_len_q) & (offs_d[None, :] < head_dim), other=0.0,
    ).to(tl.float32)

    end_n = (start_m + 1) * BLOCK_M if CAUSAL else seq_len_k
    for start_n in range(0, end_n, BLOCK_N):
        offs_n = start_n + tl.arange(0, BLOCK_N)
        kv_mask = (offs_n[:, None] < seq_len_k) & (offs_d[None, :] < head_dim)
        k = tl.load(
            K_ptr + offs_n[:, None] * stride_kn + offs_d[None, :] * stride_kk,
            mask=kv_mask, other=0.0,
        ).to(tl.float32)
        v = tl.load(
            V_ptr + offs_n[:, None] * stride_vn + offs_d[None, :] * stride_vk,
            mask=kv_mask, other=0.0,
        ).to(tl.float32)
        s = tl.dot(q, tl.trans(k)) * scale
        if CAUSAL:
            s = tl.where(offs_m[:, None] >= offs_n[None, :], s, float("-inf"))
        m_new = tl.maximum(m_i, tl.max(s, axis=1))
        p     = tl.exp(s - m_new[:, None])
        l_i   = l_i * tl.exp(m_i - m_new) + tl.sum(p, axis=1)
        acc   = acc * tl.exp(m_i - m_new)[:, None] + tl.dot(p.to(''' + tl_dtype + '''), v)
        m_i   = m_new

    acc = acc / l_i[:, None]
    tl.store(L_ptr + off_bh * seq_len_q + offs_m, m_i + tl.log(l_i), mask=offs_m < seq_len_q)
    out_mask = (offs_m[:, None] < seq_len_q) & (offs_d[None, :] < head_dim)
    tl.store(
        Out_ptr + offs_m[:, None] * stride_om + offs_d[None, :] * stride_ok,
        acc.to(''' + tl_dtype + '''), mask=out_mask,
    )


def flash_attention(q, k, v, causal=True):
    """Scaled dot-product attention. q/k/v: (B, H, S, D) CUDA tensors."""
    assert q.ndim == 4
    B, H, Sq, D = q.shape
    _, _, Sk, _ = k.shape
    BLOCK_D = triton.next_power_of_2(D)
    out = torch.empty_like(q)
    L   = torch.empty((B * H, Sq), device=q.device, dtype=torch.float32)
    grid = lambda meta: (triton.cdiv(Sq, meta["BLOCK_M"]), B * H)
    flash_attn_kernel[grid](
        q, k, v, out, L,
        q.stride(0), q.stride(1), q.stride(2), q.stride(3),
        k.stride(0), k.stride(1), k.stride(2), k.stride(3),
        v.stride(0), v.stride(1), v.stride(2), v.stride(3),
        out.stride(0), out.stride(1), out.stride(2), out.stride(3),
        B, H, Sq, Sk, D,
        1.0 / math.sqrt(D),
        CAUSAL=causal,
        BLOCK_D=BLOCK_D,
    )
    return out


if __name__ == "__main__":
    torch.manual_seed(0)
    B, H, S, D = 2, 4, 128, 64
    q = torch.randn(B, H, S, D, device=DEVICE, dtype=torch.''' + dtype.value + ''')
    k = torch.randn(B, H, S, D, device=DEVICE, dtype=torch.''' + dtype.value + ''')
    v = torch.randn(B, H, S, D, device=DEVICE, dtype=torch.''' + dtype.value + ''')
    tri = flash_attention(q, k, v, causal=True)
    ref = torch.nn.functional.scaled_dot_product_attention(q, k, v, is_causal=True)
    err = (tri.float() - ref.float()).abs().max().item()
    print(f"{'OK' if err < 0.1 else 'FAIL'}  flash_attention  max_err={err:.3f}")
'''
        )
        return TritonGenResult(
            op=TritonOp.ATTENTION,
            dtype=dtype,
            source=source,
            kernel_names=["flash_attn_kernel"],
            wrapper_names=["flash_attention"],
            autotune_configs=4,
            notes=[
                "Online-softmax: O(seq_len) HBM vs O(seq_len^2) naive.",
                "L (log-sum-exp) buffer is saved for the backward pass.",
            ],
        )


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _tl_dtype(dtype: DType) -> str:
    return {
        DType.FLOAT16:  "tl.float16",
        DType.FLOAT32:  "tl.float32",
        DType.BFLOAT16: "tl.bfloat16",
    }[dtype]


def _activation_snippet(activation: str, accumulator_var: str = "out") -> tuple[str, str]:
    """Return (code_block, note_string) for fused activation."""
    if activation == "none":
        return "", ""
    snippets = {
        "relu":    f"    {accumulator_var} = tl.maximum({accumulator_var}, 0.0)\n",
        "gelu": (
            f"    _x = {accumulator_var}\n"
            f"    {accumulator_var} = 0.5 * _x * (1.0 + tl.math.tanh("
            f"0.7978845608 * (_x + 0.044715 * _x * _x * _x)))\n"
        ),
        "sigmoid": f"    {accumulator_var} = 1.0 / (1.0 + tl.math.exp(-{accumulator_var}))\n",
        "silu": (
            f"    {accumulator_var} = {accumulator_var} * "
            f"(1.0 / (1.0 + tl.math.exp(-{accumulator_var})))\n"
        ),
    }
    code = snippets.get(activation, "")
    return code, f"Fused {activation} activation applied before output cast."
